CREATE USER teachme;
\password teachme
fD4STWxauYy3CNb4
CREATE DATABASE teachme;
\connect teachme
REVOKE CONNECT ON DATABASE teachme FROM PUBLIC;
GRANT CONNECT ON DATABASE teachme TO teachme;
/* run schema.sql */
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO teachme;
GRANT SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO teachme;
